config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'homes#index'
  resources :posts do
    resources :comments, only: [:create,:destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, :text, presence: true
  belongs_to :user
  has_many :comments

  validates :image, :text, presence: true
  validates :image, format: { with: /\A[a-zA-Z0-9-_]+\z/, message: 'はYouTubeのURLを入力してください' }

  def self.search(search)
    if search != ""
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :comments

  validates :nickname,  presence: true, length: { maximum: 6 }

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "guest"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :basic_auth

  def after_sign_in_path_for(resource)
    posts_path(resource)
  end

  private

  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
  #   end
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.save
    @comments = @post.comments.includes(:user)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]


  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    url = params[:post][:image]
    url = url.last(11)
    @post.image = url

    if @post.valid?
      @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def search
    @posts = Post.search(params[:keyword])
  end




  private

  def post_params
    params.require(:post).permit(:image, :text, :question1, :question2).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
  
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to posts_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('.comments').html('<%=j(render partial: "posts/comment", comments: @comments) %>')

$('#comment_text').val("")

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/homes/index.html.erb
<% unless user_signed_in? %>
  <div class="overview-area"> 
    <h1>Biztube-output</h1>
    <p>隙間時間に効率よく勉強したい方に向けた<br>ビジネスYouTube特化型のアウトプットサービス</p>
    <div class="search-form-area">
    </div>
  </div>
<% end %>

<% unless user_signed_in? %>
  <div class="about-service">
    <h1>Biztube-outputのサービス</h1>
    <h2>アウトプットと情報共有コミュニティ</h2>
    <h2 class="border-line">なぜアウトプットをするのか?</h2>
    <p>「インプットが3に対してアウトプットが7」。<br>これが記憶をもっとも効率化する比率だと脳科学の研究で明らかになっています。</p>
    <p>昨今のYouTubeの流行により隙間時間にも気軽に学ぶ環境が増えました。<br>それなのに、「なかなか勉強の成果が出ない」「記憶に残らない」と感じている人も多いのではないでしょうか。</p>
    <p>せっかく学んだ知識を"自分のモノ"にしてみませんか？</p>
  </div>
<% end %>

<% unless user_signed_in? %>
  <div class="invitation">
    <h1>今すぐアウトプットをはじめましょう!</h1>
    <div class="btn-top">
      <div class="signup">
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-signup" %>
      </div>
      <div class="signin">
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-signin" %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizTubeOutput</title>
    <script
    src="https://code.jquery.com/jquery-3.5.1.js"
    integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/posts">Biz-tube-output</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
            </span>
            <%= link_to "OUTPUT", new_post_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to 'ゲスト', users_guest_sign_in_path, method: :post, class: "post" %>
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>

    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright Biz-tube-output 2020.
      </p>
    </footer>
  </body>
</html>

app/views/posts/_comment.html.erb
<% @comments.each do |comment| %>
  <p id="comment_<%= comment.id %>">
    <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
    <%= comment.text %>
    <%= link_to  '削除', post_comment_path(comment.post_id, comment.id), {method: :delete, remote: true, class: "btn"} %>
  </p>
  
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.text_field :image, placeholder: "【YouTube動画】共有URLを貼ってください" %>
  <%= form.text_field :question1, placeholder: "Q. この動画から最も学べたことはなんですか？" %>
  <%= form.text_field :question2, placeholder: "Q. 学んだことを実生活にどのように活かしていこうと思いますか？" %>
  <%= form.text_area :text, placeholder: "アウトプットを記入して知識を自分のモノにしましょう！", rows: "10" %>
  <%= form.submit "SEND" %>
<% end %>

app/views/posts/_post.html.erb
<div class="content_post">
<p>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= post.image %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to 'コメント', post_path(post.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == post.user_id %>
        <li>
          <%= link_to '編集', edit_post_path(post.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', post_path(post.id), method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <span class="name">
    <a href="/users/<%= post.user.id %>">
      <span>投稿者</span><%= post.user.nickname %>
    </a>
  </span>
</div>


<div class="my-parts">
	<div class="my-parts-content">
		<ul>
      <li>
        <p>この動画から最も学べたこと：<br><%= post.question1 %></p>
      </li>
      <li>
        <p>学んだことを実生活にどう活かすか：<br><%= post.question2 %></p>
      </li>
      <li>
        <p>アウトプット：<br><%= post.text %></p>
      </li>
    </ul>
	</div>
</div>

app/views/posts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>アウトプットが完了しました。</h3>
    <a class="btn" href="/posts">アウトプット一覧へ戻る</a>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/posts">アウトプット一覧へ戻る</a>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/index.html.erb
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "アウトプットを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<%# <p class="first-text">学んだことをアウトプットしましょう</p>
<p class="first-text>人間の脳は想起するときに記憶に強く結びつくと研究で明らかになっています</p> %>
<div class="contents row">
  <% @posts.each do |post| %>
    <%= render partial: "post", locals: { post: post } %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @post, local: true) do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "アウトプットを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @posts.each do |post| %>
    <%= render partial: "post", locals: { post: post } %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="contents row">
  <div class="content_post">
  <p>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.image %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </p>
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_post_path(@post.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', post_path(@post.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <span class="name">
      <a href="/users/<%= @post.user.id %>">
        <span>投稿者</span><%= @post.user.nickname %>
      </a>
    </span>
  </div>
  <div class="my-parts">
    <div class="my-parts-content">
    <ul>
      <li>
        <p>この動画から最も学べたこと：<br><%= @post.question1 %></p>
      </li>
      <li>
        <p>学んだことを実生活にどう活かすか：<br><%= @post.question2 %></p>
      </li>
      <li>
        <p>アウトプット：<br><%= @post.text %></p>
      </li>
    </ul>
	</div>
</div>

  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@post, @comment]) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <%=render partial: "comment", comments: @comments %>
      <% end %>
    </div>
  </div>

</div>

app/views/posts/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/posts">アウトプット一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんのアウトプット一覧</p>
  <% @posts.each do |post| %>
    <%= render partial: "posts/post", locals: { post: post } %>
  <% end %>
</div>